"use client"
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Header from "../components/Header";
import { useState } from "react";
import { FareUpdateContext } from "../context/FareUpdateContext";
import { Toaster } from "sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata = {
//   title: "Car Sharing App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const [fareUpdated, setFareUpdated] = useState(false);
  return (
    <ClerkProvider>
      <FareUpdateContext.Provider value={{fareUpdated, setFareUpdated}}>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          
          {children}
          <Toaster/>
        </body>
      </html>
      </FareUpdateContext.Provider>
    </ClerkProvider>
  );
}
